### ISSUE TITLE
Build fails for Linux 5.4.28-2-lts

### ISSUE THREAD

**Issue by Saancreed** [mid-kid/r8822be#1]
Hello,

On Arch Linux building the current `master` succeds for `linux-zen`, but fails for `linux-lts` with the following error:

```
make: Entering directory '/usr/lib/modules/5.4.28-2-lts/build'
  AR      /var/lib/dkms/r8822be/20/build/built-in.a
  CC [M]  /var/lib/dkms/r8822be/20/build/base.o
  CC [M]  /var/lib/dkms/r8822be/20/build/cam.o
  CC [M]  /var/lib/dkms/r8822be/20/build/core.o
  CC [M]  /var/lib/dkms/r8822be/20/build/debug.o
  CC [M]  /var/lib/dkms/r8822be/20/build/efuse.o
  CC [M]  /var/lib/dkms/r8822be/20/build/ps.o
  CC [M]  /var/lib/dkms/r8822be/20/build/rc.o
  CC [M]  /var/lib/dkms/r8822be/20/build/regd.o
  CC [M]  /var/lib/dkms/r8822be/20/build/stats.o
  CC [M]  /var/lib/dkms/r8822be/20/build/pci.o
  CC [M]  /var/lib/dkms/r8822be/20/build/rtl8822be/fw.o
/var/lib/dkms/r8822be/20/build/base.c: In function ‘rtl_tx_agg_start’:
/var/lib/dkms/r8822be/20/build/base.c:1725:9: error: ‘IEEE80211_AMPDU_TX_START_IMMEDIATE’ undeclared (first use in this function); did you mean ‘IEEE80211_AMPDU_TX_START’?
 1725 |  return IEEE80211_AMPDU_TX_START_IMMEDIATE;
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |         IEEE80211_AMPDU_TX_START
/var/lib/dkms/r8822be/20/build/base.c:1725:9: note: each undeclared identifier is reported only once for each function it appears in
/var/lib/dkms/r8822be/20/build/base.c:1726:1: warning: control reaches end of non-void function [-Wreturn-type]
 1726 | }
      | ^
make[1]: *** [scripts/Makefile.build:266: /var/lib/dkms/r8822be/20/build/base.o] Error 1
make[1]: *** Waiting for unfinished jobs....
  CC [M]  /var/lib/dkms/r8822be/20/build/rtl8822be/hw.o
make: *** [Makefile:1691: /var/lib/dkms/r8822be/20/build] Error 2
make: Leaving directory '/usr/lib/modules/5.4.28-2-lts/build'
```

I suspect the issue might be caused by commit 56fb4ec237ab98813035f848ee04593cc692b5bf, and fwiw LTS builds were successful at f592380ea65e4ca9e0ac1a376e6c4677ddce52ce. [Here](https://gist.github.com/Saancreed/8b64fa13a96abcd0d692c9ffb7259ca4) are my `PKGBUILD` and `dkms.conf`, which I used to create the package.

**Comment by mid-kid** [comment]
Reverted affecting commit. Shouldn't cause many problems for newer kernels anyway.
