### ISSUE TITLE
Build fails on Linux 5.6.8-zen1 due to incompatible pointer type

### ISSUE THREAD

**Issue by Saancreed** [mid-kid/r8822be#2]
I believe the issue is caused by upstream commit https://github.com/torvalds/linux/commit/c3c6201ad35b8ca05ff782161d87f639a83de5a9, which changed the type of `rate_control_ops.alloc` struct member.

```
DKMS make.log for r8822be-21 for kernel 5.6.8-zen1-1-zen (x86_64)
Thu Apr 30 10:07:41 CEST 2020
make: Entering directory '/usr/lib/modules/5.6.8-zen1-1-zen/build'
  AR      /var/lib/dkms/r8822be/21/build/built-in.a
  CC [M]  /var/lib/dkms/r8822be/21/build/cam.o
  CC [M]  /var/lib/dkms/r8822be/21/build/base.o
  CC [M]  /var/lib/dkms/r8822be/21/build/debug.o
  CC [M]  /var/lib/dkms/r8822be/21/build/core.o
  CC [M]  /var/lib/dkms/r8822be/21/build/efuse.o
  CC [M]  /var/lib/dkms/r8822be/21/build/ps.o
  CC [M]  /var/lib/dkms/r8822be/21/build/rc.o
  CC [M]  /var/lib/dkms/r8822be/21/build/regd.o
/var/lib/dkms/r8822be/21/build/rc.c:288:11: error: initialization of ‘void * (*)(struct ieee80211_hw *)’ from incompatible pointer type ‘void * (*)(struct ieee80211_hw *, struct dentry *)’ [-Werror=incompatible-pointer-types]
  288 |  .alloc = rtl_rate_alloc,
      |           ^~~~~~~~~~~~~~
/var/lib/dkms/r8822be/21/build/rc.c:288:11: note: (near initialization for ‘rtl_rate_ops.alloc’)
  CC [M]  /var/lib/dkms/r8822be/21/build/stats.o
cc1: some warnings being treated as errors
make[1]: *** [scripts/Makefile.build:268: /var/lib/dkms/r8822be/21/build/rc.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:1683: /var/lib/dkms/r8822be/21/build] Error 2
make: Leaving directory '/usr/lib/modules/5.6.8-zen1-1-zen/build'
```

**Comment by mid-kid** [comment]
I hate to be like this but it's currently working on my 5.6.4 kernel, and I probably won't be updating for a bit.
For now you can apply this patch:
```diff
diff --git a/rc.c b/rc.c
index 7f59470..1d4641b 100644
--- a/rc.c
+++ b/rc.c
@@ -250,7 +250,7 @@ static void rtl_rate_update(void *ppriv,
 {
 }
 
-static void *rtl_rate_alloc(struct ieee80211_hw *hw, struct dentry *debugfsdir)
+static void *rtl_rate_alloc(struct ieee80211_hw *hw)
 {
        struct rtl_priv *rtlpriv = rtl_priv(hw);
        return rtlpriv;
```
Or submit a pull-request with an `ifdef` that at least works on your side.
